version: "3.3"
services:
  document-db:
    container_name: "document-db"
    image: mysql:latest
    restart: always
    ports:
      - "3000:3306"
    environment:
      MYSQL_USER: "document"
      MYSQL_PASSWORD: "document"
      MYSQL_DATABASE: "cartha_document_db"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - net
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  document:
    container_name: "document"
    restart: on-failure:20
    build:
      context: .
      dockerfile: document.Dockerfile
    depends_on:
      - document-db
    links:
      - document-db
    ports:
      - "4000:8080"
    environment:
      DATABASE_HOST: "document-db"
      DATABASE_PORT: "3306"
      DATABASE_NAME: "cartha_document_db"
      DATABASE_USER: "document"
      DATABASE_PASSWORD: "document"
    networks:
      - net

  node-a:
    container_name: "node_a"
    build:
      context: .
      dockerfile: node.Dockerfile
    depends_on:
      - node-manager
    links:
      - node-manager
    ports:
      - "5001:8080"
    networks:
      - net
    environment:
#      NODE_ID: "1"
      NODE_MANAGER_URL: "http://node_manager:8080"

  node-b:
    container_name: "node_b"
    build:
      context: .
      dockerfile: node.Dockerfile
    depends_on:
      - node-manager
    links:
      - node-manager
    ports:
      - "5002:8080"
    networks:
      - net
    environment:
#      NODE_ID: "2"
      NODE_MANAGER_URL: "http://node_manager:8080"

  node-manager-db:
    container_name: "node-manager-db"
    image: mysql:latest

    restart: always
    ports:
      - "3002:3306"
    environment:
      MYSQL_USER: "node-manager"
      MYSQL_PASSWORD: "node-manager"
      MYSQL_DATABASE: "node_manager_db"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - net
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  node-manager:
    container_name: "node_manager"
    restart: on-failure:20
    build:
      context: .
      dockerfile: nodeManager.Dockerfile
    environment:
      DATABASE_HOST: "node-manager-db"
      DATABASE_PORT: "3306"
      DATABASE_NAME: "node_manager_db"
      DATABASE_USER: "node-manager"
      DATABASE_PASSWORD: "node-manager"
    depends_on:
      - node-manager-db
    links:
      - node-manager-db
    ports:
      - "5003:8080"
    networks:
      - net

  authentication-db:
    container_name: "authentication-db"
    image: mysql:latest
    restart: always
    ports:
      - "3001:3306"
    environment:
      MYSQL_USER: "authentication"
      MYSQL_PASSWORD: "authentication"
      MYSQL_DATABASE: "authentication_db"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - net
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  authentication:
    container_name: "authentication"
    build:
      context: .
      dockerfile: authentication.Dockerfile
    restart: on-failure:20
    links:
      - authentication-db
    depends_on:
      - authentication-db
    ports:
      - "7000:8080"
    environment:
      DATABASE_HOST: "authentication-db"
      DATABASE_PORT: "3306"
      DATABASE_NAME: "authentication_db"
      DATABASE_USER: "authentication"
      DATABASE_PASSWORD: "authentication"
    networks:
      - net

  ui:
    container_name: "ui"
    build:
      context: .
      dockerfile: ui.Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_MANAGER_URL: "http://node_manager:8080"
      AUTHENTICATION_URL: "http://authentication:8080"
    networks:
      - net

networks:
  net:
