version: "3.3"
services:
  document-db:
    container_name: "document-db"
    image: mysql:latest
    restart: always
    ports:
      - "3000:3306"
    expose:
      - "3000"
    environment:
      MYSQL_USER: "document"
      MYSQL_PASSWORD: "document"
      MYSQL_DATABASE: "cartha_document_db"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - net
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  document:
    container_name: "document"
    build:
      context: .
      dockerfile: document.Dockerfile
    depends_on:
      - document-db
    links:
      - document-db
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: "document-db"
      DATABASE_PORT: "3306"
      DATABASE_NAME: "cartha_document_db"
      DATABASE_USER: "document"
      DATABASE_PASSWORD: "document"
    networks:
      - net

networks:
  net:
